### ISSUE TITLE
2 copies?

### ISSUE THREAD

**Issue by AlekseyMartynov** [NickMitrokhin/mytestrep#4]
Митрохич!

https://github.com/NickMitrokhin/mytestrep/tree/master/example/php/DevExtreme
https://github.com/NickMitrokhin/mytestrep/tree/master/DevExtreme

Why?

**Comment by NickMitrokhin** [comment]
Cause, it's is legacy. The content of the "example" folder was copied from another folder that was deployed on the Apache server. It is supposed that the folder with the service.php and DataController.php files should contain the DevExtreme folder with DevExtremePHPData files. Do you think that it is better to remove it and describe in README that the "example" folder should contain "DevExtreme" or so?

**Comment by AlekseyMartynov** [comment]
> Cause, it's is legacy.

Haha. This project hasn't been released yet. Strange to have any legacy stuff in it 😃 

> the folder with the service.php and DataController.php files should contain the DevExtreme folder

That's not always true. In the context of a shared web hosting - yes. But in environments where DocumentRoot can be controlled, this is not necessary. Web site can include libraries outside of www root. Ultimately, it's better to work on calculating URL (https://github.com/NickMitrokhin/mytestrep/blob/5e481613427f28bc8fc1fd24ec6e84b3ca55a75d/example/js/index.js#L2) rather than have 2 copies of the library. Let's discuss it tomorrow.

**Comment by NickMitrokhin** [comment]
ok
